#!/usr/bin/env bash
# Prints details of subdomains present for a particular domain

multipleDomains() {
for subdomain in "www" "lb-01" "web-01" "web-02"
do
cmd="$subdomain"."$1"
filter="/^[a-z]/ { print \"The subdomain \" subdomain \" is a \" \$4 \" record and points to \" \$5 }"

dig $cmd | awk -v subdomain="$subdomain" "$filter"
done
}

singleDomain() {
subdomain="$2"
cmd="$subdomain"."$1"
filter="/^[a-z]/ { print \"The subdomain \" subdomain \" is a \" \$4 \" record and points to \" \$5 }"

dig $cmd | awk -v subdomain="$subdomain" "$filter"
}

if [ "$#" -eq 1 ]
then
	multipleDomains "$1"
elif [ "$#" -eq 2 ]
then
	singleDomain "$1" "$2"
fi
