#!/usr/bin/env bash
# Transfers a file from the client to the server
FILEPATH=$1
IPADDR=$2
USERNAME=$3
KEYPATH=$4

if [[ $# < 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sudo scp -i $KEYPATH $FILEPATH $USERNAME@$IPADDR:
fi
