#!/usr/bin/env bash
# Installs nginx web server and configurations

sudo apt update
sudo apt install -y nginx
ufw allow "Nginx HTTP"

echo "Hello World!" > /var/www/html/index.html
service nginx start
