#!/usr/bin/env bash
# Installs nginx web server and configurations

apt update
apt install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "
http {
        server {
                listen 80;
                root /var/www/html/;
        }
}

events {}" > /etc/nginx/nginx.conf

nginx -s reload
service nginx start
