#!/usr/bin/env bash
# Performs redirection to web server

sudo sed -i '/server_name _;/a\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
