#!/usr/bin/env bash
# This scripts replaces port 8080 in nginx conf with port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx start
