#!/usr/bin/env bash
# story from passwd file

file=/etc/passwd

while IFS=":" read -r uname pass uid gid uinfo hd csh
do
	echo "The user $uname is part of the $gid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pass, more info about the user here: $uinfo"
done < $file
