#!/usr/bin/env bash
# Script that prints diggerent text for 4th and 8th iteration

i=1
while (( i <= 10 ))
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
