#!/usr/bin/env bash
# configures ubuntu server with localhost and facebook

if grep -q localhost /etc/hosts
then
	cp /etc/hosts ~/hosts.new
	sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
else
	echo -e "127.0.0.2\tlocalhost" >> /etc/hosts
fi

if grep -q facebook /etc/hosts
then
	cp /etc/hosts ~/hosts.new
	sudo sed -i 's/31.13.66.35/8.8.8.8/' ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
else
	echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
fi
